### PR TITLE
Feature/entry points

### PR DESCRIPTION
**Pull request by srossross**
@malev this will enable conda-server-build to register itself as a subcommand when installed.

requires https://github.com/Anaconda-Server/clyent/pull/1

### CODE REVIEW

**Comment by malev** [comment]
@srossross this is breaking the tests

**Comment by srossross** [comment]
@malev, yes it requires `clyent v0.4`

**Comment by malev** [comment]
@srossross I've tried `pip` and `conda` and I can't install `clyent` `0.4`

**Comment by srossross** [comment]
It is not released yet. sorry

**Comment by srossross** [comment]
@malev, tests are passing now.

**Comment by malev** [comment]
then merge!

**Pull request merged**
